# Site settings
title: natanael.arndt.xyz
email:
description: "This is my part of the web, where I publish some ideas. Some as longer posts and some in short status messages, which should be somehow my part of a distributed twitter."
baseurl: ""
url: "https://natanael.arndt.xyz"
github_username:  white-gecko
webid: "https://natanael.arndt.xyz/#i"
mastodon_user: "chaos.social/@white_gecko"
stackoverflow_uri: https://stackoverflow.com/users/414075/white-gecko
googleplus_uri: https://plus.google.com/109221747073615777107?rel=author
wikipedia-de_username: "white_gecko"
excerpt_separator: <!--more-->

# Build settings
permalink: /:year/:month/:day/:title
timezone: Europe/Berlin
markdown: kramdown
kramdown:
  parse_block_html: true

# Build settings
#theme: minima
plugins:
  - jekyll-rdf
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
jekyll_rdf:
    path: "_data/graph.ttl"
    restriction: "SELECT ?resourceUri WHERE { ?resourceUri ?p ?o . FILTER regex(str(?resourceUri), \"https://natanael.arndt.xyz/\") }"
    class_template_mappings:
        "http://purl.org/dc/terms/BibliographicResource" : "publication.html"
        "http://xmlns.com/foaf/0.1/Document" : "page.html"
