version: '3'

vars:
  WORKING_DIRECTORY: '{{.github.workspace | default .PWD}}'
  BUNDLE_PATH: '.vendor'
  ID_UID:
    sh: id -u
  ID_GID:
    sh: id -g
  TARGET: '{{.TARGET | default "_site"}}'
  BUILD_WATCH_FILES: find . -name '*' -not -path "./.git/*" -not -path "./.git" -not -path "./.jekyll-cache/*" -not -path "./.jekyll-cache" -not -path "./{{.TARGET}}" -not -path "./{{.TARGET}}/*"

tasks:

  default:
    desc: List the available tasks
    cmds:
      - task -l

  ci:
    desc: CI Target to build the page
    cmds:
      - task: build

  data:
    desc: Build the graph.ttl file
    cmds:
      - |
        cd _data
        cat projects.ttl bib.ttl extra.ttl > graph.ttl
      - task: bib:update

  bib:update:
    desc: Update the ttl files for the individual bibliography resources
    cmds:
      - |
        cd _data
        rm -r bib || true
        poetry run python extract.py --file bib.ttl --base https://natanael.arndt.xyz/ --selection selection.sparql
        cd ..
        rm -r ttl/bib || true
        cp -r _data/bib ttl/

  build:
    desc: Build the page from source
    cmds:
      - task: build:docker
        vars:
          LANGUAGE: de
          TARGET: '{{.TARGET}}'

  build:docker:
    desc: Build the page from source using docker
    vars:
      JEKYLL_UID: '{{.JEKYLL_UID | default .ID_UID}}'
      JEKYLL_GID: '{{.JEKYLL_GID | default .ID_GID}}'
      JEKYLL_USER_ARG:
        sh: '[ "$(docker info --format "{{`{{if .Host.Security.Rootless}}true{{end}}`}}")" = "true" ] || echo -u "{{.JEKYLL_UID}}:{{.JEKYLL_GID}}"'
      JEKYLL_IMAGE: ghcr.io/aksw/jekyll-rdf:4.2.4
    cmds:
      - |
        docker run --rm \
        --workdir /github/workspace \
        -v {{.WORKING_DIRECTORY}}:/github/workspace:z \
        -e TZ=Europe/Berlin {{.JEKYLL_USER_ARG}} -e BUNDLE_PATH={{.BUNDLE_PATH}} \
        {{.JEKYLL_IMAGE}} jekyll build -d {{.TARGET}}

  watch:
    desc: Serve the page and rebuild it on changes
    deps:
      - task: serve
      - task: build:watch
    cmds:
      - echo "Terminate"

  build:watch:
    desc: Watch for changes in the directory and rebuild the page, should be combined with task serve in a second terminal
    cmds:
      - '{{.BUILD_WATCH_FILES}} | entr task build'

  serve:
    desc: Serve the locally built site
    cmds:
      - python -m http.server --directory {{.TARGET}}

  clean:
    desc: Clean up temporary direcotries
    cmds:
      - rm -r .vendor .jekyll-cache .bundle
